[package]
name = "uc_api"
version = "0.4.0-alpha"
authors = ["Markus Zehnder <markus.z@unfoldedcircle.com>"]
license = "Apache-2.0"
description = "Unfolded Circle API model"
edition = "2021"
#repository = "https://github.com/TODO"
#documentation = "TODO"

[dependencies]
# JSON (de)serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "1"

# Helpful macros for working with enums and strings
strum = "0.24"
strum_macros = "0.24"
derive_more = "0.99"
