[package]
name = "uc_api"
version = "0.6.0-alpha"
authors = ["Markus Zehnder <markus.z@unfoldedcircle.com>"]
license = "Apache-2.0"
description = "Unfolded Circle API model"
edition = "2021"
repository = "https://github.com/unfoldedcircle/api-model-rs"

[dependencies]
# JSON (de)serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "1"

chrono = { version = "0.4" , features = ["serde"] }

# Helpful macros for working with enums and strings
strum = "0.24"
strum_macros = "0.24"
derive_more = "0.99"

validator = "0.14"
validator_derive = "0.14"
regex = "1"
lazy_static = "1"

[dependencies.sqlx]
version = "0.5"
default-features = false
features = [
    "chrono",
    "json",
]
optional = true
