// This file is @generated by prost-build.
/// Audio stream specification.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AudioConfiguration {
    /// Optional. Number of audio channels. Default: 1
    #[prost(uint32, tag = "1")]
    pub channels: u32,
    /// Audio sample rate in Hz.
    #[prost(uint32, tag = "2")]
    pub sample_rate: u32,
    /// Audio sample format.
    #[prost(enumeration = "SampleFormat", tag = "3")]
    pub sample_format: i32,
    /// Optional. Default: PCM
    #[prost(enumeration = "AudioFormat", tag = "4")]
    pub format: i32,
}
/// Start of an audio stream session.
/// As long as the stream is active, `RemoteVoiceData` messages are sent containing audio chunks.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoteVoiceBegin {
    /// Audio session identifier that will be used in follow-up RemoteVoicePayload and RemoteVoiceEnd messages.
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    /// Audio stream specification for data sent in the follow-up RemoteVoicePayload messages.
    #[prost(message, optional, tag = "2")]
    pub configuration: ::core::option::Option<AudioConfiguration>,
}
/// Audio chunk in an audio stream session.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoteVoiceData {
    /// Audio session identifier from RemoteVoiceBegin.
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    /// Audio chunk.
    #[prost(bytes = "bytes", tag = "2")]
    pub samples: ::prost::bytes::Bytes,
}
/// End of an audio stream session.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoteVoiceEnd {
    /// Audio session identifier from RemoteVoiceBegin.
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
}
/// Supported audio frame formats.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SampleFormat {
    Unknown = 0,
    /// Signed 8 bit
    I8 = 1,
    /// Signed 16 bit
    I16 = 2,
    /// Signed 32 bit
    I32 = 3,
    /// Unsigned 8 bit
    U8 = 4,
    /// Unsigned 16 bit
    U16 = 5,
    /// Unsigned 32 bit
    U32 = 6,
    /// Float 32 bit
    F32 = 7,
}
impl SampleFormat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "SAMPLE_FORMAT_UNKNOWN",
            Self::I8 => "I8",
            Self::I16 => "I16",
            Self::I32 => "I32",
            Self::U8 => "U8",
            Self::U16 => "U16",
            Self::U32 => "U32",
            Self::F32 => "F32",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SAMPLE_FORMAT_UNKNOWN" => Some(Self::Unknown),
            "I8" => Some(Self::I8),
            "I16" => Some(Self::I16),
            "I32" => Some(Self::I32),
            "U8" => Some(Self::U8),
            "U16" => Some(Self::U16),
            "U32" => Some(Self::U32),
            "F32" => Some(Self::F32),
            _ => None,
        }
    }
}
/// Supported audio codec formats.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AudioFormat {
    Unknown = 0,
    Pcm = 1,
}
impl AudioFormat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "AUDIO_FORMAT_UNKNOWN",
            Self::Pcm => "PCM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AUDIO_FORMAT_UNKNOWN" => Some(Self::Unknown),
            "PCM" => Some(Self::Pcm),
            _ => None,
        }
    }
}
/// All available integration messages.
///
/// Allows direct binary WebSocket message serialization and deserialization.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IntegrationMessage {
    #[prost(oneof = "integration_message::Message", tags = "1, 2, 3")]
    pub message: ::core::option::Option<integration_message::Message>,
}
/// Nested message and enum types in `IntegrationMessage`.
pub mod integration_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Message {
        /// Start of an audio stream session.
        #[prost(message, tag = "1")]
        VoiceBegin(super::RemoteVoiceBegin),
        /// Audio chunk in an audio stream session.
        #[prost(message, tag = "2")]
        VoiceData(super::RemoteVoiceData),
        /// End of an audio stream session.
        #[prost(message, tag = "3")]
        VoiceEnd(super::RemoteVoiceEnd),
    }
}
