blank_issues_enabled: false
contact_links:
  - name: Unfolded Circle Community Forum
    url: http://unfolded.community/
    about: Please ask and answer questions here.
  - name: Unfolded Circle Discord Channel
    url: http://unfolded.chat/
    about: Chat with the community and for asking questions.
  - name: Unfolded Circle Contact Form
    url: https://unfoldedcircle.com/contact
    about: Write us a message on our website.
